config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations", :omniauth_callbacks =>  "users/omniauth_callbacks" }
  resources :users, only: [:index, :show]
  
  
  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated  do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :posts
  resources :friendship
  resources :friend_request
  resources :comments
  resources :likes

  get 'users_index' => 'users#index'
  resources :profile
 
  
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  has_one :post
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def new
    @comment = Comment.new
    @post = Post.find(comment_params[:post])
  end
  
  def create
    @comment = Comment.new
    @comment.user_id = create_params[:user_id]
    @comment.post_id = create_params[:post_id]
    @comment.comment = create_params[:comment]
    if @comment.save
      flash[:success]="Comment created"
      redirect_to '/'
    end
  end
  
  def destroy
    @comment = Comment.find(comment_params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
      flash[:success] = "Your comment has been archived against your wishes ;)   "
    end
    redirect_to '/'
  end
  
  
  
  
  
  private
  
  def comment_params
    params.permit( :author, :post, :id)
  end
  
  def create_params
    params.require(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_new_comment.html.erb
<%= form_for @comment, url: comments_path do |t| %>
  <%= t.text_field :comment, :placeholder => "Jump into the middle... " %>
  <%= t.hidden_field :user_id, value: current_user.id %>
  <%= t.hidden_field :post_id, value: post_id %>
  <%= t.submit "Submit a comment" %>
<% end %>

app/views/comments/new.html.erb
<div class="new_comment">
  <div class="individual_post" >
      <p class="author"><%= User.find(@post.author).username %><small> wrote:</small></p>
      <p class="title"><%= @post.title %></p>
      <p class="content"><%= @post.content %></p>
      <p class="post_time">Posted at <%= @post.created_at %></p>
  
  <%= form_for @comment do |f| %>
    <%= f.text_area :comment %>
    <%= f.label :comment, "Comment" %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "Submit your comment" %>
  <% end %>
  

  
</div>