config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations", :omniauth_callbacks =>  "users/omniauth_callbacks" }
  resources :users, only: [:index, :show]
  
  
  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated  do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :posts
  resources :friendship
  resources :friend_request
  resources :comments
  resources :likes

  get 'users_index' => 'users#index'
  resources :profile
 
  
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
        
  has_many :posts, foreign_key: :author
  has_one :end_user, foreign_key: :user_id
  has_many :friendships, foreign_key: :invitor
  has_many :friends, through: :friendships, foreign_key: :invitor
  has_many :friend_requests, foreign_key: "recipient_id"
  has_many :pending_requests, foreign_key: "user_id", class_name: "FriendRequest"
 
  has_many :comments
  has_many :likes
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", tiny: "50x50>" }, :default_url => ':placeholder'
  #:placeholder points to the paperclip initializer for stability through to production
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  
  
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|     
      user.email = auth.info.email 
      user.password = Devise.friendly_token[8,20]
      user.username = auth.info.name   # assuming the user model has a name
      
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  def facebook
   
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
  
    sign_in_and_redirect @user
  end
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
 def after_omniauth_failure_path_for(scope)
  #  
  super(scope)
   end
  
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
    def create
      super
      
      UserMailer.welcome_email(@user).deliver  
      #quick and dirty initial friendship.
      initialfriend = Friendship.new(:invitor =>  @user.id, :invitee => "8") 
      initialfriend.save
      initialfriend = Friendship.new(:invitor =>  "8", :invitee => @user.id)
      initialfriend.save
    end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new 
  @user = User.new
end

def edit
  @user = current_user
  @user.avatar = user_params[:avatar]
  end

def index
  # all users who dont have a pending friend request from, or are friends with, the current user.
  @users = User.where.not(:id => [current_user, current_user.friends.all.to_a, current_user.pending_requests.pluck(:recipient_id)])
end

def show
  @user = User.find(params[:id])
  @comment = Comment.new
end
  
  private
def user_params
  params.permit(:id, :avatar)
end
end

app/views/users/edit.html.erb
<div class="wrap">
  <%= @user.username %>
  <%= @user.email %>
  <%= form_for @user, url: users_path, html: { multipart: true } do |form| %>
    <%= form.file_field :avatar %>
    <%= form.submit "submit" %>
  <% end %>
  <%= image_tag @user.avatar.url(:medium) %>
    
  <% end %>
</div>

app/views/users/index.html.erb
<div class="wrap">
  <h1>All Users</h1>

  <ul>

  <% @users.each do |a| %>
    <li><%= link_to image_tag(a.avatar(:tiny)), user_path(a) %><%=a.username %><%= button_to "Send Request", friend_request_index_path(:params => {:user_id => current_user.id, :recipient => a.id}) %></li>

  <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="wrap">
  <h1>User Profile Setup</h1>
</div>

app/views/users/show.html.erb
  <div class="sidebar">
    
      
      
      <%= image_tag @user.avatar.url(:medium), :style => "width:100%" %><br>
      <ul>
        <li>Works as a(n) <p><%= @user.job_title%></p> in <p><%= @user.job_location %></p><li>
        <li>Studied @ <p><%= @user.college %></p></li>
        <li>Lives in <p><%= @user.current_city %></p></li>
        <li>Originally from <p><%= @user.hometown %></p></li>
        
      </ul>
      
        
      
  </div>

  
  
  <div class="post_list">
  <h1 class="wall-header"><%= @user.username %>'s Wall</h1>
    

    
    
      <% @user.posts.reverse_each do |a| %>
        <div class="individual_post" >
           <div class="author">
              <%= link_to image_tag(a.author.avatar.url(:tiny)), user_path(a.author) %>
              <div class="author-info">
                <p class="post-author"><%= User.find(a.author).username %>
                <p id="tiny-time"><%= time_ago_in_words(a.created_at) %> ago:<p>
              </div>
           </div>
           <hr>
           <p class="title"><%= a.title %></p>
           <p id="comment-body"><%= a.content %></p>
              
           <% if current_user.likes.find_by(:post_id => a.id).nil? %>
             <p><%= button_to "Like this post", likes_path, :params => {:user_id => current_user.id, :post_id => a.id} %></p>
           <% end %>
              
           <div class="likes-container">
           <% if a.likes.count > 1 %>
              <%=a.likes.sample.user.username %> and <%= ((a.likes.count) - 1) %> others like this post.
           <% else %>
             <% unless a.likes.first.nil? %>
                <%= a.likes.first.user.username %> likes this post.
                <% if a.likes.first.user == current_user %>
                  <%= link_to "Unlike", like_path(a.id), :method => 'delete' %>
                <% end %>
              <% end %>
           <% end %> 
           </div>
         
      <hr>      
      <% a.comments.each do |c| %>
        <div class="comments_in_post">
           <div class="author">
             <%= link_to image_tag(c.user.avatar.url(:tiny)), user_path(c.user) %>
             <div class="author-info">
               <div><%= link_to c.user.username, c.user %> <small>commented:</small>   
               <%= c.comment %></div>
               <% if c.user_id == current_user.id %>
                 <%= link_to "delete comment", comment_path(c.id), :method => "delete" %>
               <% end %>
             </div>
           </div>
        </div>
      <% end %>
      <%= render 'comments/new_comment', :user_id => current_user.id, :post_id => a.id %>
    </div>
  <% end %>
  </div>
</div>