config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations", :omniauth_callbacks =>  "users/omniauth_callbacks" }
  resources :users, only: [:index, :show]
  
  
  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated  do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :posts
  resources :friendship
  resources :friend_request
  resources :comments
  resources :likes

  get 'users_index' => 'users#index'
  resources :profile
 
  
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :author
  has_many :comments
  has_many :likes
  has_many :likers, through: :likes, :source => "user"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.author = User.find(post_params[:author])
    @post.content = post_params[:content]
    @post.save
    redirect_to authenticated_root_path
  end
  
  
  def index
    @posts = wall
    @post = Post.new
    @comment = Comment.new
    
 end 
  private
  
  def post_params
    params.require(:post).permit(:author, :title, :content)
  end
  
  def wall # populate users wall with posts from friends and self sorted by time of update
    @posts = Post.where(:author => [ current_user.id, current_user.friends.to_a]).order(:updated_at).reverse_order
  end
    
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_post.html.erb
<div class="post-creation" >
  <%= form_for(@post, url: posts_path) do |f| %>
    <%= f.label :title, "Title of Post" %>
    <%= f.text_field :title %><br>
    
    <%= f.label :content, "Post" %>
    <%= f.text_area :content %>
    
    <%= f.hidden_field :author,value:  current_user.id %>
    
    <%= f.submit "Create this Post" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="sidebar">
    
    <%= image_tag current_user.avatar.url(:medium), :style =>"width:99%" %>
    
    
    <div class="sidebar-friends">
      <%= button_to "Make some new friends", users_index_path, method: :get%>
      
      <% if current_user.friend_requests.count != 0 %>
        <p>You have active friend requests from the following users</p>
        <% current_user.friend_requests.each do |a| %>
          <p><%= link_to image_tag(a.user.avatar.url(:tiny)), user_path(a.user) %>
          <%= User.find(a.user_id).username %></p>
          <p> <%= button_to "Accept Friend Request", friendship_index_path, :params => {:invitee => a.user_id, :invitor => current_user.id} %></p>
          <p> <%= button_to "Delete Friend Request", friend_request_path(a), :params => {:user_id => a.user_id, :recipient_id => current_user.id}, method: :delete %></p>
        <% end %>
      <% end %>
      <p> Friends List: </p>
      <ul>
        <% current_user.friends.each do |a| %>
          <li>
            <%= image_tag a.avatar.url(:tiny) %>
            <%= link_to a.username, user_path(a) %> 
          </li>
        <% end %>
      </ul>
    </div>
</div>
  
  
<div class="post_list">
  <h1 class="wall-header"><%= current_user.username %>'s Wall</h1>
    
  <%= form_for @post, :url => {:action => "create"} do |t| %>
    <%= t.text_area :content, :placeholder => "Share your thoughts...", rows: 4, cols: 40 %>
    <%= t.hidden_field :author ,value:  current_user.id %>
    <%= t.submit "Submit Post" %>
  <% end %>
    
    
      <% @posts.each do |a| %>
        <div class="individual_post" >
           <div class="author">
              <%= link_to image_tag(a.author.avatar.url(:tiny)), user_path(a.author) %>
              <div class="author-info">
                <p class="post-author"><%= User.find(a.author).username %>
                <p id="tiny-time"><%= time_ago_in_words(a.created_at) %> ago:<p>
              </div>
           </div>
           <hr>
           <p class="title"><%= a.title %></p>
           <p id="comment-body"><%= a.content %></p>
              
           <% if current_user.likes.find_by(:post_id => a.id).nil? %>
             <p><%= button_to "Like this post", likes_path, :params => {:user_id => current_user.id, :post_id => a.id} %></p>
           <% end %>
              
           <div class="likes-container">
           <% if a.likes.count > 1 %>
              <%=a.likes.sample.user.username %> and <%= ((a.likes.count) - 1) %> others like this post.
           <% else %>
             <% unless a.likes.first.nil? %>
                <%= a.likes.first.user.username %> likes this post.
                <% if a.likes.first.user == current_user %>
                  <%= link_to "Unlike", like_path(a.id), :method => 'delete' %>
                <% end %>
              <% end %>
           <% end %> 
           </div>
         
      <hr>      
      <% a.comments.each do |c| %>
        <div class="comments_in_post">
           <div class="author">
             <%= link_to image_tag(c.user.avatar.url(:tiny)), user_path(c.user) %>
             <div class="author-info">
               <div><%= link_to c.user.username, c.user %> <small>commented:</small>   
               <%= c.comment %></div>
               <% if c.user_id == current_user.id %>
                 <%= link_to "delete comment", comment_path(c.id), :method => "delete" %>
               <% end %>
             </div>
           </div>
        </div>
      <% end %>
      <%= render 'comments/new_comment', :user_id => current_user.id, :post_id => a.id %>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post-creation" >
  <%= form_for(@post, url: posts_path) do |f| %>
    <%= f.label :title, "Title of Post" %>
    <%= f.text_field :title %><br>
    
    <%= f.label :content, "Post" %>
    <%= f.text_area :content %>
    
    <%= f.hidden_field :author,value:  current_user.id %>
    
    <%= f.submit "Create this Post" %>
  <% end %>
</div>